version: '3'
services:
  wms-proxy:
    build: .
    ports:
      - "5555:5555"
    environment:
      - UPSTREAM_WMS=${UPSTREAM_WMS}
      - PROXY_ADDRESS=${PROXY_ADDRESS}
      - PORT=5555
    restart: unless-stopped
